"""add contacts model 2

Revision ID: 625c4f236cb3
Revises: 99ed05ba5699
Create Date: 2025-09-14 18:10:31.247221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625c4f236cb3'
down_revision: Union[str, Sequence[str], None] = '99ed05ba5699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'avatar')
    # ### end Alembic commands ###
