"""add contacts model

Revision ID: 99ed05ba5699
Revises: 1e185a0eeb90
Create Date: 2025-09-14 17:37:15.125989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ed05ba5699'
down_revision: Union[str, Sequence[str], None] = '1e185a0eeb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birthdate', sa.Date(), nullable=False))
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('additional_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('contacts', 'birthdate')
    # ### end Alembic commands ###
