"""add a avatar field for user schema

Revision ID: bd599813eed5
Revises: eddd34793272
Create Date: 2025-09-17 18:12:03.169688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd599813eed5"
down_revision: Union[str, Sequence[str], None] = "eddd34793272"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar", sa.String(length=255), nullable=True))
    # op.execute("UPDATE users SET is_verified = False WHERE is_verified IS NULL")
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("users", "avatar")
    # ### end Alembic commands ###
