"""add is_verified on User table

Revision ID: eddd34793272
Revises: ff3b9c490625
Create Date: 2025-09-14 19:29:27.997066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eddd34793272"
down_revision: Union[str, Sequence[str], None] = "ff3b9c490625"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###
